// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxYjMuckALTLRqF4Nn6pHuOuqIfN9et3A',
    appId: '1:645889841302:android:92402a66da1bae5cc40ab7',
    messagingSenderId: '645889841302',
    projectId: 'fir-authentication-ff8eb',
    databaseURL: 'https://fir-authentication-ff8eb-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-ff8eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb50mPx5YIlcb-NBUcNWLjUipIajZAKX8',
    appId: '1:645889841302:ios:bb059e7ffa7315cac40ab7',
    messagingSenderId: '645889841302',
    projectId: 'fir-authentication-ff8eb',
    databaseURL: 'https://fir-authentication-ff8eb-default-rtdb.firebaseio.com',
    storageBucket: 'fir-authentication-ff8eb.appspot.com',
    iosClientId: '645889841302-a6uclilr4m2eg4cgoec9lmmdl83n09mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authLesson9',
  );
}
